In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from gluonts.dataset.repository.datasets import get_dataset, dataset_recipes
from gluonts.dataset.util import to_pandas

import torch
print(torch.__version__)

2.10.0+cu126

# Load Datasets from Gluonts

In [3]:
print(f"Available datasets: {list(dataset_recipes.keys())}")

Available datasets: ['constant', 'exchange_rate', 'solar-energy', 'electricity', 'traffic', 'exchange_rate_nips', 'electricity_nips', 'traffic_nips', 'solar_nips', 'wiki2000_nips', 'wiki-rolling_nips', 'taxi_30min', 'kaggle_web_traffic_with_missing', 'kaggle_web_traffic_without_missing', 'kaggle_web_traffic_weekly', 'm1_yearly', 'm1_quarterly', 'm1_monthly', 'nn5_daily_with_missing', 'nn5_daily_without_missing', 'nn5_weekly', 'tourism_monthly', 'tourism_quarterly', 'tourism_yearly', 'cif_2016', 'london_smart_meters_without_missing', 'wind_farms_without_missing', 'car_parts_without_missing', 'dominick', 'fred_md', 'pedestrian_counts', 'hospital', 'covid_deaths', 'kdd_cup_2018_without_missing', 'weather', 'm3_monthly', 'm3_quarterly', 'm3_yearly', 'm3_other', 'm4_hourly', 'm4_daily', 'm4_weekly', 'm4_monthly', 'm4_quarterly', 'm4_yearly', 'm5', 'uber_tlc_daily', 'uber_tlc_hourly', 'airpassengers', 'australian_electricity_demand', 'electricity_hourly', 'electricity_weekly', 'rideshare_without_missing', 'saugeenday', 'solar_10_minutes', 'solar_weekly', 'sunspot_without_missing', 'temperature_rain_without_missing', 'vehicle_trips_without_missing', 'ercot', 'ett_small_15min', 'ett_small_1h']

In [ ]:
d_name = "exchange_rate"
dataset = get_dataset(d_name, regenerate=False)
dataset.metadata

In [ ]:
# to TimeSeriesDataSet
train_iter = iter(dataset.train)
test_iter = iter(dataset.test)

data_df = pd.DataFrame(columns=['datetime', 'sensor', 'value'])
for i in range(int(dataset.metadata.feat_static_cat[0].cardinality)):
    train_entry = next(train_iter)
    test_entry = next(test_iter)

    train_series = to_pandas(train_entry)
    test_series = to_pandas(test_entry)

    sensor_readings = pd.concat([train_series, test_series[train_series.index[-1]+1:]]).to_frame(name='value')
    sensor_readings.reset_index(inplace=True, names=['datetime'])
    sensor_readings['sensor'] = i

    data_df = pd.concat([data_df, sensor_readings])

data_df = data_df.astype(dict(datetime='datetime64[ns]', sensor=str))

time_idx_df = pd.DataFrame(data_df['datetime'].unique(), columns=["datetime"]).sort_values(by="datetime").reset_index(drop=True).reset_index(names="time_idx")
data_df = pd.merge(data_df, time_idx_df, left_on="datetime", right_on="datetime", how="left")

data_df.to_csv("../datasets/%s.csv"%(d_name), index=False)
print(data_df.shape[0])
print(data_df.head())

In [5]:
!pip install tables

Collecting tables
  Downloading tables-3.10.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy>=1.20.0 in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from tables) (1.26.4)
Requirement already satisfied: numexpr>=2.6.2 in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from tables) (2.14.1)
Requirement already satisfied: packaging in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from tables) (24.2)
Collecting py-cpuinfo (from tables)
  Using cached py_cpuinfo-9.0.0-py3-none-any.whl.metadata (794 bytes)
Collecting blosc2>=2.3.0 (from tables)
  Downloading blosc2-4.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: typing-extensions>=4.4.0 in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from tables) (4.14.1)
Collecting ndindex (from blosc2>=2.3.0->tables)
  Downloading ndindex-1.10.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.6 kB)
Requirement already satisfied: msgpack in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from blosc2>=2.3.0->tables) (1.1.2)
Requirement already satisfied: requests in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from blosc2>=2.3.0->tables) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from requests->blosc2>=2.3.0->tables) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from requests->blosc2>=2.3.0->tables) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from requests->blosc2>=2.3.0->tables) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/seyed/forked/Sundial/.conda/lib/python3.11/site-packages (from requests->blosc2>=2.3.0->tables) (2026.1.4)
Downloading tables-3.10.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 36.0 MB/s  0:00:00m0:00:01
Downloading blosc2-4.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 32.7 MB/s  0:00:00
Downloading ndindex-1.10.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (516 kB)
Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Installing collected packages: py-cpuinfo, ndindex, blosc2, tables
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [tables]2m3/4 [tables]
Successfully installed blosc2-4.0.0 ndindex-1.10.1 py-cpuinfo-9.0.0 tables-3.10.2

(15123, 207)

# Load Datasets from H5

In [67]:
d_name = "pems03_flow"  # pems-bay, metr-la, pemsd7m, gz-metro, hz-metro, pems03_flow, pems04_flow, pems07_flow, pems08_flow, seattle
data_df = pd.read_hdf("../datasets/%s.h5"%(d_name))
print(data_df.shape)

(26208, 358)

In [68]:


data_df.reset_index(inplace=True)
data_df['time_idx'] = np.arange(data_df.shape[0])
data_df.rename(columns={'index':'datetime'}, inplace=True)

data_df = pd.melt(data_df, id_vars=[data_df.columns[0], data_df.columns[-1]], var_name='sensor', value_vars=data_df.columns[1:-1])
data_df = data_df.astype(dict(sensor=int, time_idx=int))
data_df = data_df.astype(dict(sensor=str))
print(data_df.shape)
print(data_df.head())

data_df.to_csv("../datasets/%s.csv"%("pems03_flow"), index=False)

(9382464, 4)
   datetime  time_idx sensor  value
0         0         0      0   20.0
1         1         1      0   22.0
2         2         2      0   22.0
3         3         3      0   50.0
4         4         4      0   37.0

In [60]:
data_df

,datetime,0,1,2,3,4,5,6,7,8,...,349,350,351,352,353,354,355,356,357,time_idx
0,0,20.0,20.0,182.0,182.0,91.0,182.0,136.0,91.0,91.0,...,63.0,63.0,63.0,125.0,114.0,63.0,63.0,115.0,63.0,0
1,1,22.0,22.0,174.0,174.0,87.0,174.0,131.0,87.0,87.0,...,62.0,62.0,62.0,144.0,109.0,62.0,63.0,109.0,62.0,1
2,2,22.0,22.0,183.0,183.0,92.0,183.0,139.0,92.0,92.0,...,57.0,57.0,57.0,131.0,116.0,57.0,57.0,115.0,57.0,2
3,3,50.0,49.0,137.0,139.0,60.0,158.0,111.0,57.0,55.0,...,109.0,30.0,58.0,106.0,102.0,52.0,111.0,88.0,48.0,3
4,4,37.0,35.0,128.0,123.0,54.0,131.0,111.0,46.0,52.0,...,77.0,31.0,55.0,109.0,127.0,49.0,109.0,76.0,47.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26203,26203,54.0,53.0,120.0,128.0,66.0,149.0,110.0,56.0,61.0,...,63.0,35.0,67.0,51.0,147.0,59.0,134.0,144.0,48.0,26203
26204,26204,52.0,55.0,109.0,107.0,58.0,126.0,114.0,51.0,55.0,...,65.0,36.0,72.0,61.0,143.0,64.0,139.0,130.0,61.0,26204
26205,26205,43.0,39.0,144.0,143.0,55.0,147.0,99.0,62.0,61.0,...,89.0,32.0,55.0,61.0,132.0,57.0,124.0,104.0,47.0,26205
26206,26206,27.0,27.0,115.0,114.0,62.0,129.0,91.0,41.0,47.0,...,50.0,35.0,61.0,72.0,132.0,56.0,123.0,112.0,39.0,26206
26207,26207,48.0,52.0,108.0,105.0,56.0,120.0,103.0,33.0,36.0,...,62.0,34.0,52.0,41.0,108.0,56.0,134.0,115.0,38.0,26207

In [14]:
def load_brussels(data_name=None):
    """
    Load data from CSV and return np.ndarray of shape (T, 145).

    test set will be defined as last 10% of time steps, outside of this function.
    """
    data = pd.read_csv(
        "/home/seyed/PycharmProjects/step/STEP/datasets/Bru/merged_data.csv",
        index_col=0,
        parse_dates=[0],
    )
    data = (
        data.interpolate(method="spline", order=3, limit_area="inside")
            .ffill()
            .bfill()
    )
    # data.values is (T, 145)
    return data


data_df = load_brussels()
print(data_df.shape)

(15123, 207)

In [8]:
df_2024 = pd.read_csv("/home/seyed/Documents/BM_data_2024/process/debug_final_pivot_data_2023-12-30_2079-04-24.csv", parse_dates=["start_timestamp"])

In [10]:
df_2024 = df_2024[(df_2024.start_timestamp > pd.Timestamp("2024-01-01 00:00")) & (df_2024.start_timestamp < pd.Timestamp("2024-01-31 00:00"))]

In [12]:
df_2024.to_csv("/home/seyed/forked/T3Time/scripts/brussels.csv", index=True)

In [15]:
# detect columns with ratio of zero values > 0.5 and drop them
zero_ratio = (data_df == 0).mean(axis=0)
prune_data_df = data_df.loc[:, zero_ratio <= 0.5]

print(f"Remaining columns: {prune_data_df.shape[1]}")

Remaining columns: 195

In [17]:
data_df.to_csv("/home/seyed/forked/T3Time/scripts/brussels.csv", index=True)

In [18]:
data_df.head()

,BXLAND031448F1,BXLAND031450F1,BXLAND031451F1,BXLAND034219F1,BXLAND034220F1,BXLAND034221F1,BXLAND034222F1,BXLAND034224F1,BXLAND034225F1,BXLAND034232F1,...,BXLKOE034178F1,BXLKOE034179F1,BXLKOE037164B1,BXLKOE037165B1,BXLKOE037167B1,BXLKOE126857B1,BXLKOE126918F1,BXLKOE126923F1,BXLKOE126924F1,BXLKOE126925F1
start_timestamp,,,,,,,,,,,,,,,,,,,,,
2023-11-19 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-11-19 00:05:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-11-19 00:10:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-11-19 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-11-19 00:20:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [71]:
d_name = "brussels"

In [154]:
filtered_columns = data_df.loc[:, zero_ratio <= 0.5].columns

In [79]:
prune_data_df.drop(["start_timestamp"], axis=1, inplace=True)

/tmp/ipykernel_2992361/3542680190.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prune_data_df.drop(["start_timestamp"], axis=1, inplace=True)

In [80]:
prune_data_df.columns[-2], prune_data_df.columns[-1]

('time_idx', 'datetime')

In [83]:
prune_data_df.columns[0:-2]

Index(['BXLAND031448F1', 'BXLAND031450F1', 'BXLAND031451F1', 'BXLAND034219F1',
       'BXLAND034220F1', 'BXLAND034221F1', 'BXLAND034222F1', 'BXLAND034224F1',
       'BXLAND034225F1', 'BXLAND034232F1',
       ...
       'BXLKOE034178F1', 'BXLKOE034179F1', 'BXLKOE037164B1', 'BXLKOE037165B1',
       'BXLKOE037167B1', 'BXLKOE126857B1', 'BXLKOE126918F1', 'BXLKOE126923F1',
       'BXLKOE126924F1', 'BXLKOE126925F1'],
      dtype='object', length=195)

In [65]:
d_name = "brussels"

In [84]:
# prune_data_df.reset_index(inplace=True)
# prune_data_df['time_idx'] = np.arange(prune_data_df.shape[0])
# prune_data_df.rename(columns={'index':'datetime'}, inplace=True)
# prune_data_df['datetime'] = pd.date_range(start='2023-11-19 00:00:00', periods=len(prune_data_df['start_timestamp']), freq='5min')
prune_data_df = pd.melt(prune_data_df, id_vars=[prune_data_df.columns[-2], prune_data_df.columns[-1]], var_name='sensor', value_vars=prune_data_df.columns[0:-2])
prune_data_df = prune_data_df.astype(dict(sensor=str, time_idx=int))
prune_data_df = prune_data_df.astype(dict(sensor=str))
print(prune_data_df.shape)
print(prune_data_df.head())

prune_data_df.to_csv("../datasets/%s.csv"%(d_name), index=False)

(2948985, 4)
   time_idx            datetime          sensor  value
0         0 2023-11-19 00:00:00  BXLAND031448F1    0.0
1         1 2023-11-19 00:05:00  BXLAND031448F1    0.0
2         2 2023-11-19 00:10:00  BXLAND031448F1    0.0
3         3 2023-11-19 00:15:00  BXLAND031448F1    0.0
4         4 2023-11-19 00:20:00  BXLAND031448F1    0.0

import pickle

In [1]:
import json

with open('/media/seyed/D2DA77DADA77B975/BM/data/1/18/raw_data.txt', 'r') as f:
    raw_data = json.load(f)

JSONDecodeError: Extra data: line 3396 column 2 (char 110963)

In [6]:
pd.json_normalize(raw_data)

,_aggregation_id,_creation_timestamp,_end_timestamp,_expiration,_start_timestamp,_type,_update_timestamp,count,period,subtype,...,speed_classes.[30;40[,speed_classes.[40;50[,speed_classes.[50;60[,speed_classes.[0;10[,speed_classes.[60;70[,speed_classes.[70;80[,speed_classes.[80;90[,speed_classes.[90;100[,speed_classes.[110;120[,speed_classes.[100;110[
0,1700465700000#PT5M#lightVehicle#null#5f883210a...,2023-11-20 07:39:14.246000,2023-11-20 07:35:00,2023-11-25 07:39:11.228000,2023-11-20 07:30:00,counting,2023-11-20 07:39:14.246000,1,PT5M,counting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1700465700000#PT5M#lightVehicle#null#5f883629a...,2023-11-20 07:39:14.246000,2023-11-20 07:35:00,2023-11-25 07:39:11.233000,2023-11-20 07:30:00,counting,2023-11-20 07:39:14.246000,1,PT5M,counting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1700465700000#PT5M#lightVehicle#BE#5a78690b48d...,2023-11-20 07:39:14.246000,2023-11-20 07:35:00,2023-11-25 07:39:11.242000,2023-11-20 07:30:00,counting,2023-11-20 07:39:14.246000,45,PT5M,counting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1700465700000#PT5M#lightVehicle#BE#5a33df4d53e...,2023-11-20 07:39:14.246000,2023-11-20 07:35:00,2023-11-25 07:39:11.234000,2023-11-20 07:30:00,counting,2023-11-20 07:39:14.246000,52,PT5M,counting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1700465700000#PT5M#lightVehicle#BE#5f02b5cb73b...,2023-11-20 07:39:14.246000,2023-11-20 07:35:00,2023-11-25 07:39:11.245000,2023-11-20 07:30:00,counting,2023-11-20 07:39:14.246000,70,PT5M,counting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160078,1700520600000#PT5M#lightVehicle#5f9132ce6905da...,2023-11-20 22:54:46.191000,2023-11-20 22:50:00,2023-11-25 22:54:46.168000,2023-11-20 22:45:00,NaN,2023-11-20 22:54:46.191000,1,PT5M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160079,1700520600000#PT5M#lightVehicle#6023eda249afa4...,2023-11-20 22:54:46.191000,2023-11-20 22:50:00,2023-11-25 22:54:46.168000,2023-11-20 22:45:00,NaN,2023-11-20 22:54:46.191000,25,PT5M,NaN,...,NaN,19.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160080,1700520600000#PT5M#lightVehicle#5f7d875ead2d18...,2023-11-20 22:54:46.191000,2023-11-20 22:50:00,2023-11-25 22:54:46.168000,2023-11-20 22:45:00,NaN,2023-11-20 22:54:46.191000,6,PT5M,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160081,1700520600000#PT5M#lightVehicle#5f9135cb6905da...,2023-11-20 22:54:46.191000,2023-11-20 22:50:00,2023-11-25 22:54:46.168000,2023-11-20 22:45:00,NaN,2023-11-20 22:54:46.191000,4,PT5M,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160082,1700520600000#PT5M#lightVehicle#5f9135cb6905da...,2023-11-20 22:54:46.191000,2023-11-20 22:50:00,2023-11-25 22:54:46.167000,2023-11-20 22:45:00,NaN,2023-11-20 22:54:46.191000,4,PT5M,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
dfs = []
for key in raw_data:
    dfs.append(pd.json_normalize(key))
dfs = pd.concat(dfs)

In [8]:
ddd = dfs[dfs["subtype"] == "counting"]

In [9]:
ddd.columns

Index(['_aggregation_id', '_creation_timestamp', '_end_timestamp',
       '_expiration', '_start_timestamp', '_type', '_update_timestamp',
       'count', 'period', 'subtype', 'type', 'vehicle_type',
       'location.coordinates', 'location.type', 'source.name.fr',
       'source.name.vi', 'source.name.nl', 'source.name.de',
       'source.name.nl-BE', 'source.name.en', 'source.id', 'source._id',
       'nationality', 'source.name.fr-BE', 'measures', 'median_duration',
       'median_speed', 'resources.name.fr', 'resources.name.vi',
       'resources.name.nl', 'resources.name.de', 'resources.name.nl-BE',
       'resources.name.en', 'resources.id', 'resources._id',
       'speed_classes.[20;30[', 'speed_classes.[10;20[',
       'speed_classes.[30;40[', 'speed_classes.[40;50[',
       'speed_classes.[50;60[', 'speed_classes.[0;10[',
       'speed_classes.[60;70[', 'speed_classes.[70;80[',
       'speed_classes.[80;90[', 'speed_classes.[90;100[',
       'speed_classes.[110;120[', 'speed_classes.[100;110['],
      dtype='object')

In [10]:
locations = {}

for key in ddd["source.id"].drop_duplicates():
    locations[key] = ddd.loc[ddd["source.id"] == key]["location.coordinates"].iloc[0]

In [11]:
locations

{'BXLAND135656B1': [4.324086, 50.844197],
 'BXLAND135417B1': [4.325761, 50.845194],
 'BXLMOL034189F1': [4.334110920203833, 50.856668996612875],
 'BXLBXL125638B1': [4.388069172608651, 50.84146550625018],
 'BXLBXL031438F1': [4.326966, 50.898064],
 'BXLFOR034193F1': [4.30547721101096, 50.801439162695424],
 'BXLIXL127916F1': [4.353909486966835, 50.82260947052188],
 'BXLUCC034677F1': [4.335111107242816, 50.77474764098082],
 'BXLWSP034669F1': [4.465217682070772, 50.835227877859985],
 'BXLSCH035888F1': [4.398806, 50.85517],
 'BXLEVE128267B1': [4.402418653845467, 50.865947845015896],
 'BXLUCC034162F1': [4.348713194870293, 50.80380801132337],
 'BXLWSL134917F1': [4.445405006408691, 50.85540008544922],
 'BXLAND135516F1': [4.291268, 50.817075734445154],
 'BXLBXL034148F1': [4.341321270109129, 50.85304966482994],
 'BXLAUD134958F1': [4.43453636441803, 50.8133750525088],
 'BXLWSL128296F1': [4.432437509705303, 50.860020199212215],
 'BXLETT034023F1': [4.393060207366943, 50.82422637939453],
 'BXLMOL135416B1': [4.333292, 50.849567],
 'BXLBXL138177B1': [4.366707, 50.849369],
 'BXLWSL036644F1': [4.458663812164307, 50.848520087049735],
 'BXLSCH036936F1': [4.40258845822709, 50.8496992707588],
 'BXLBXL133452B1': [4.342614650726318, 50.83431240229132],
 'BXLWSL134916F1': [4.4456490278244, 50.8557432245577],
 'BXLMOL034190F1': [4.335332612831117, 50.84990895864516],
 'BXLSTG034218F1': [4.356337521550327, 50.83133108345385],
 'BXLBXL127216F1': [4.363242244375571, 50.853537632728134],
 'BXLBXL135918B1': [4.367423804739459, 50.842784602836275],
 'BXLAUD133166F1': [4.450963729973712, 50.81847549429321],
 'BXLJET031440F1': [4.313989580672611, 50.89296442716894],
 'BXLWSP035084F1': [4.466597, 50.838916],
 'BXLBXL127956F1': [4.430688022925536, 50.87824680306208],
 'BXLBXL035824F1': [4.356087965612636, 50.87820179122335],
 'BXLKOE031685F1': [4.312112, 50.864484],
 'BXLBXL036926B1': [4.3424376249313354, 50.83440048966804],
 'BXLIXL135836F1': [4.3786702156066895, 50.82976531982422],
 'BXLAND031450F1': [4.30703833614329, 50.816042289929804],
 'BXLBXL131688B1': [4.357636, 50.833269],
 'BXLWSL034932F1': [4.415339759407774, 50.85348518493258],
 'BXLIXL034130B1': [4.36685, 50.81701],
 'BXLJET126903F1': [4.334124272126988, 50.879339176412145],
 'BXLAUD034150F1': [4.425460077475222, 50.81669737967059],
 'BXLAND134656F1': [4.284453630447388, 50.83778833953028],
 'BXLBXL134998F1': [4.326524, 50.898005],
 'BXLMOL034188F1': [4.333731651306152, 50.85750961303711],
 'BXLJET135757B1': [4.317123176900078, 50.88513971742131],
 'BXLBXL037146B1': [4.348724, 50.858001],
 'BXLBXL034102F1': [4.36314248887002, 50.900944028217985],
 'BXLMOL035893F1': [4.290008193143643, 50.846316062446675],
 'BXLJET126904F1': [4.333170042534679, 50.87639904778273],
 'BXLBXL034099F1': [4.357484817504883, 50.90125274658203],
 'BXLBXL125637B1': [4.3789644911197065, 50.840312742641224],
 'BXLSTG1358964F1': [4.34264, 50.82669],
 'BXLAND031451F1': [4.307182103263386, 50.81605638680528],
 'BXLBSA137640B1': [4.292556652778626, 50.8689941454021],
 'BXLKOE126925F1': [4.31878623525719, 50.86572426086616],
 'BXLEVE034011F1': [4.421567161230364, 50.860558490061074],
 'BXLETT135537F1': [4.385083198547363, 50.83967971801758],
 'BXLSTJ127017F1': [4.368327, 50.852491],
 'BXLSCH034092F1': [4.403449992973328, 50.84915707256718],
 'BXLBXL125717B1': [4.386950060188293, 50.84374325276008],
 'BXLBXL135669B1': [4.363129923942566, 50.85366768998995],
 'BXLIXL034127F1': [4.401589870452881, 50.81763458251953],
 'BXLBXL034134F1': [4.347028330024719, 50.858356681540556],
 'BXLSCH125736B1': [4.408869611141968, 50.8509110976247],
 'BXLEVE134936F1': [4.4112321990854655, 50.87636606703603],
 'BXLGAN034171F1': [4.307933330535889, 50.869510650634766],
 'BXLBXL136779B1': [4.366139, 50.853194],
 'BXLKOE126918F1': [4.330173492431641, 50.86325454711914],
 'BXLEVE128266B1': [4.402178656272577, 50.866546255025106],
 'BXLBXL034065F1': [4.406692624092103, 50.88313132614391],
 'BXLBXL133136F1': [4.3948956, 50.891623],
 'BXLJET127338F1': [4.309007036990877, 50.891336576914334],
 'BXLSTJ125836B1': [4.369381206344252, 50.848967583438906],
 'BXLSTG035906F1': [4.34475362985684, 50.827228478534984],
 'BXLBXL137276B1': [4.3623299914016735, 50.846774743088275],
 'BXLIXL125896F1': [4.364025, 50.835221],
 'BXLKOE037165B1': [4.32184, 50.865565],
 'BXLWSL130256F1': [4.415266991790506, 50.85350300503815],
 'BXLMOL037149B1': [4.336115, 50.861739],
 'BXLBSA034176F1': [4.287298683251747, 50.87102207461173],
 'BXLWSL130257F1': [4.415286221319773, 50.85369842550525],
 'BXLBXL035885F1': [4.362361, 50.846611],
 'BXLBXL036945F1': [4.432212, 50.878752],
 'BXLSCH135497F1': [4.398729389879647, 50.854675928421244],
 'BXLAND134439F1': [4.307290259899617, 50.816059518556195],
 'BXLBXL036925F1': [4.352629, 50.856888],
 'BXLWSL034256F1': [4.445870246303789, 50.85549601500148],
 'BXLBXL034141B1': [4.357553, 50.833472],
 'BXLSCH034085F1': [4.38738, 50.852629],
 'BXLSTJ034082F1': [4.3728350383097885, 50.84992944514183],
 'BXLUCC034675F1': [4.356711982803345, 50.773958245365975],
 'BXLBSA126936F1': [4.287307753485967, 50.87109518207515],
 'BXLGAN037166B1': [4.317785, 50.867983],
 'BXLSCH034075F1': [4.358517536706784, 50.86209822410237],
 'BXLSCH135496F1': [4.398329841603251, 50.85471785678655],
 'BXLAND036505F1': [4.283313257040838, 50.819401744810506],
 'BXLAND034686F1': [4.270017981529236, 50.83263532244504],
 'BXLBSA034174F1': [4.280674700686011, 50.86704375645706],
 'BXLSCH034093F1': [4.4091361725788945, 50.85154721137858],
 'BXLBXL034136F1': [4.365123271942139, 50.85409927368164],
 'BXLEVE127996F1': [4.421149587798228, 50.86099399981172],
 'BXLSCH034066F1': [4.38415002822876, 50.87998580932617],
 'BXLBXL134405B1': [4.399113, 50.839188],
 'BXLEVE034064F1': [4.410425186157227, 50.878055572509766],
 'BXLSTG035905F1': [4.344353580144763, 50.82724015195623],
 'BXLUCC034674F1': [4.364334072832353, 50.77318440855595],
 'BXLBXL134700B1': [4.386537, 50.842473],
 'BXLSCH135877F1': [4.365166, 50.869546],
 'BXLSCH135878F1': [4.362484, 50.86915],
 'BXLBXL136780F1': [4.366128444671631, 50.85293960571289],
 'BXLSCH034084F1': [4.387567754631042, 50.852584973536636],
 'BXLAND034244F1': [4.281331539154054, 50.83518988066149],
 'BXLSCH137656B1': [4.371472, 50.860667],
 'BXLJET139437F1': [4.317746, 50.885196],
 'BXLAND131299F1': [4.306916235405576, 50.824820051667466],
 'BXLBXL134156B1': [4.405107381648669, 50.90589620284314],
 'BXLWSL034254F1': [4.44931173324585, 50.85187911987305],
 'BXLGAN134660F1': [4.316757917404175, 50.87784455670038],
 'BXLSCH036928F1': [4.402771, 50.849218],
 'BXLEVE035891F1': [4.4215973454958535, 50.86068157649025],
 'BXLWSL034008F1': [4.445632934570312, 50.85571274673805],
 'BXLSCH034087F1': [4.398726463317871, 50.855499267578125],
 'BXLAND034220F1': [4.264508247375488, 50.817413330078125],
 'BXLMOL031446F1': [4.284856107535633, 50.845614617160905],
 'BXLBXL037144B1': [4.348898, 50.858008],
 'BXLBXL034245F1': [4.3517339880181956, 50.90113129513921],
 'BXLSCH034088F1': [4.398017906745911, 50.855238657305506],
 'BXLBSA034175F1': [4.287355285790425, 50.87130720468804],
 'BXLSCH034068B1': [4.365085, 50.86942301060918],
 'BXLAUD031459F1': [4.445425033569336, 50.8092041015625],
 'BXLSCH034074F1': [4.360478, 50.865939999999995],
 'BXLBXL034144F1': [4.340676784515381, 50.83781814575195],
 'BXLAND034224F1': [4.298703193664551, 50.84666061401367],
 'BXLUCC034679F1': [4.319036349702835, 50.79175237284153],
 'BXLBXL125716B1': [4.386806, 50.84321],
 'BXLBXL133486B1': [4.350478887557983, 50.833814366688216],
 'BXLKOE037167B1': [4.31551, 50.866413],
 'BXLSCH034086F1': [4.387503381614685, 50.85263915994719],
 'BXLWSP034665F1': [4.465487, 50.84169399999999],
 'BXLEVE032498B1': [4.41185, 50.875922],
 'BXLBXL036927B1': [4.350419878959656, 50.83386518689119],
 'BXLSCH128265B1': [4.400525, 50.859533],
 'BXLBSA126899F1': [4.280473170273718, 50.86716814954436],
 'BXLAND034221F1': [4.271934737448776, 50.83618158708799],
 'BXLSCH128264B1': [4.400770209735986, 50.85934077794505],
 'BXLBXL035886B1': [4.356448, 50.84003],
 'BXLBXL135577F1': [4.357667, 50.832972],
 'BXLIXL138098F1': [4.378736786036007, 50.82957012349672],
 'BXLKOE037164B1': [4.321685, 50.865891],
 'BXLBXL034146F1': [4.338516712188721, 50.844974517822266],
 'BXLEVE128059F1': [4.421780665158074, 50.86080812761133],
 'BXLEVE133176B1': [4.417906, 50.871347],
 'BXLBXL125635B1': [4.379093, 50.84035],
 'BXLWAT034151F1': [4.423159907777457, 50.801364901812306],
 'BXLUCC034687F1': [4.325183333333333, 50.7851278],
 'BXLBXL036934F1': [4.356168270111084, 50.87800979614258],
 'BXLBXL138180B1': [4.362631797790527, 50.847171783447266],
 'BXLWAT034152F1': [4.426244963041571, 50.80486296709283],
 'BXLUCC034676F1': [4.33983588218689, 50.77446268680728],
 'BXLKOE034178F1': [4.319714705329582, 50.86552602042699],
 'BXLUCC034131F1': [4.341163684394165, 50.8026894504583],
 'BXLAND034238B1': [4.334706, 50.838992],
 'BXLUCC034678F1': [4.326591666666666, 50.7869389],
 'BXLUCC034680F1': [4.311856746673584, 50.797855377197266],
 'BXLEVE032499F1': [4.411489691150896, 50.876284828750926],
 'BXLAUD134956F1': [4.434683322906494, 50.814029693603516],
 'BXLSCH034095F1': [4.368028, 50.859583000000015],
 'BXLKOE126857B1': [4.321622, 50.865867],
 'BXLSCH034090F1': [4.397669792175293, 50.8548469543457],
 'BXLSTG131276F1': [4.356552234010803, 50.83130304121802],
 'BXLUCC034158B1': [4.359375179330273, 50.814359657399685],
 'BXLBXL135670F1': [4.36346818650818, 50.85352421105188],
 'BXLWSP135596F1': [4.431495, 50.827772],
 'BXLMOL135964B1': [4.329672, 50.847038],
 'BXLSCH034070F1': [4.37192, 50.869958],
 'BXLFOR034205F1': [4.339536124572088, 50.81529207946081],
 'BXLUCC127336F1': [4.400510583548227, 50.79652293287663],
 'BXLETT034018F1': [4.385510362901702, 50.83954253098207],
 'BXLBXL032497F1': [4.432849896760887, 50.878835611135855],
 'BXLIXL034140F1': [4.362167954444885, 50.83745295336243],
 'BXLSCH137336F1': [4.383941650390625, 50.87992477416992],
 'BXLAUD138737F1': [4.445582559524537, 50.80907349171085],
 'BXLUCC135956F1': [4.34099956154801, 50.80272824567106],
 'BXLETT036933F1': [4.406317400382345, 50.83489502147237],
 'BXLUCC031453F1': [4.3184372186660775, 50.795839604778564],
 'BXLBXL135917F1': [4.368639, 50.845472],
 'BXLBXL138020B1': [4.36232328414917, 50.84687042236328],
 'BXLBXL138019B1': [4.361773490905762, 50.84736633300781],
 'BXLAND135936F1': [4.330642, 50.842256],
 'BXLAUD034247F1': [4.408195313029307, 50.81547283675745],
 'BXLAND031448F1': [4.291178226470947, 50.81702423095703],
 'BXLJET036668B1': [4.3122510366916424, 50.89252407481097],
 'BXLBXL127997F1': [4.345189504492551, 50.90205663109715],
 'BXLAND135658B1': [4.317981, 50.838356],
 'BXLBXL034078F1': [4.363315610529086, 50.85351865368374],
 'BXLBXL034133F1': [4.347081974205017, 50.85865466913896],
 'BXLMOL035892F1': [4.330021858215332, 50.849056243896484],
 'BXLSTG034142F1': [4.350652536706784, 50.833448791464235],
 'BXLBXL034100F1': [4.35937176330377, 50.90094830436826],
 'BXLBXL035825F1': [4.3948956, 50.891623],
 'BXLBXL035887F1': [4.354917, 50.836083],
 'BXLAND034222F1': [4.284458994865417, 50.83776801316449],
 'BXLAND135659B1': [4.325222, 50.844922],
 'BXLEVE127976F1': [4.421667352874488, 50.86092573255233],
 'BXLGAN035894F1': [4.29923152923584, 50.872840881347656],
 'BXLAUD134937B1': [4.442864, 50.810052],
 'BXLJET139439F1': [4.3169023234652855, 50.88526983885072],
 'BXLUCC031452F1': [4.3183943033218375, 50.7956293764891],
 'BXLGAN034170F1': [4.308258533477783, 50.869476318359375],
 'BXLSTJ034137F1': [4.369611, 50.846833],
 'BXLSCH036944F1': [4.403036, 50.849121],
 'BXLSTJ034079F1': [4.366514451884071, 50.8545739298697],
 'BXLAND034225F1': [4.280125141143799, 50.8250732421875],
 'BXLUCC034672F1': [4.386493, 50.785999],
 'BXLBXL034147F1': [4.340179920196533, 50.85164260864258],
 'BXLBXL034077F1': [4.358603499525505, 50.855267328533046],
 'BXLAND034232F1': [4.30661153793335, 50.82464599609375],
 'BXLAND135356B1': [4.281210755958557, 50.82528170291113],
 'BXLAND034685F1': [4.271740401515529, 50.827426991095734],
 'BXLMOL037147B1': [4.343083, 50.859667],
 'BXLSTG034215F1': [4.353665580496596, 50.82301201142627],
 'BXLSTG127439F1': [4.345103, 50.826616],
 'BXLBXL138018B1': [4.350861549377441, 50.84214782714844],
 'BXLAND034240F1': [4.281409784163468, 50.83444088267558],
 'BXLKOE126923F1': [4.3193479200297205, 50.86555341931582],
 'BXLSCH135436B1': [4.397814728836059, 50.85520790831046],
 'BXLAND131286F1': [4.335116037698796, 50.839101998482555],
 'BXLBSA137641B1': [4.2922991607131955, 50.869116021839545],
 'BXLBXL034250F1': [4.4069562023773186, 50.90494990848066],
 'BXLBXL034104F1': [4.404752975364917, 50.905868293985776],
 'BXLBSA131672F1': [4.29287958209856, 50.874669757739646],
 'BXLAND135419B1': [4.318169, 50.838519],
 'BXLUCC127456F1': [4.348694405016973, 50.80393846430967],
 'BXLMOL034242F1': [4.285028671526021, 50.845984599223804],
 'BXLUCC034156F1': [4.337679, 50.810159],
 'BXLBXL034138F1': [4.369001260700104, 50.845508664140254],
 'BXLSTG138077B1': [4.34039831161499, 50.83788299560547],
 'BXLBXL034098F1': [4.34817021889656, 50.90087073232269],
 'BXLMOL131860F1': [4.335402350265504, 50.84988186386184],
 'BXLBXL138097B1': [4.3561978723526, 50.84006048806751],
 'BXLKOE034179F1': [4.330353260040283, 50.863380432128906],
 'BXLEVE032496B1': [4.412369, 50.875597],
 'BXLUCC031454F1': [4.32666490613576, 50.782043599171416],
 'BXLBXL138697F1': [4.407324, 50.904684],
 'BXLBXL136829B1': [4.35823, 50.848435],
 'BXLBXL135560F1': [4.3385467529296875, 50.84496307373047],
 'BXLBXL128057F1': [4.341316680681215, 50.8531884457192],
 'BXLBXL127256F1': [4.432083, 50.878611],
 'BXLKOE126924F1': [4.319133656253098, 50.86562615190157],
 'BXLAND039685F1': [4.283090930948062, 50.819611715926115],
 'BXLSCH135476B1': [4.358086, 50.862225],
 'BXLGAN034172F1': [4.320876565147882, 50.867572353536175],
 'BXLBXL034097F1': [4.345019148549208, 50.90202853780988],
 'BXLAUD127156F1': [4.425426789952075, 50.81659849130342],
 'BXLBXL036931F1': [4.399184, 50.839237],
 'BXLAND034219F1': [4.2647673744548715, 50.8175418897953],
 'BXLAND034239F1': [4.32922, 50.832651],
 'BXLSCH135456F1': [4.387946605682373, 50.85245132446289],
 'BXLAND134658F1': [4.284239053726196, 50.83768331987832],
 'BXLUCC126856F1': [4.382716441500063, 50.76935297750347],
 'BXLSCH034072F1': [4.362766, 50.869043],
 'BXLAND135418B1': [4.323769, 50.844025],
 'BXLFOR131857F1': [4.321596835999634, 50.82224594075048],
 'BXLAUD134957B1': [4.434302447746277, 50.81338728449262],
 'BXLBXL035884F1': [4.35811323303961, 50.84847344674523],
 'BXLIXL126557F1': [4.36375, 50.835286],
 'BXLSTJ034080F1': [4.367764949798584, 50.85287857055664],
 'BXLWSP034009F1': [4.431968, 50.827658],
 'BXLMOL135876F1': [4.344745284336856, 50.863900755608114],
 'BXLSTG035904F1': [4.343982641511211, 50.82693788101081],
 'BXLWSL135576B1': [4.449347222222222, 50.8517194],
 'BXLFOR034196F1': [4.321522948899335, 50.822103346371904],
 'BXLSCH034096F1': [4.371528, 50.860611],
 'BXLSTG034211F1': [4.345219187858798, 50.826742389328984],
 'BXLAND134657F1': [4.28465211391449, 50.83785948174085],
 'BXLSCH034091F1': [4.397939147154554, 50.85469192842848],
 'BXLAUD036804F1': [4.450916044147864, 50.8183128160386],
 'BXLBXL031435F1': [4.346766, 50.900606],
 'BXLIXL125897B1': [4.364321, 50.834752],
 'BXLIXL125796B1': [4.36214922508026, 50.83721630616971],
 'BXLQCAM3': [4.326679, 50.898018],
 'BXLUCC127337F1': [4.4005062359745, 50.796287307594206],
 'BXLWSL034931F1': [4.43235, 50.860097],
 'BXLMOL137316F1': [4.330361, 50.849611],
 'BXLUCC034673F1': [4.367713, 50.772737],
 'BXLJET034164F1': [4.307762492007967, 50.89193212861363],
 'BXLMOL037148B1': [4.343028, 50.859639],
 'BXLWSP034668B1': [4.467805625136551, 50.83737896946547],
 'BXLFOR034200F1': [4.326767429922661, 50.82430798477237],
 'BXLBXL135916F1': [4.368981838226318, 50.84549331665039],
 'BXLSTJ034083F1': [4.3776020418038035, 50.849846530353126],
 'BXLBXL034246B1': [4.366516978899205, 50.90006316248403],
 'BXLWSL036932F1': [4.407874238073335, 50.83948818685364],
 'BXLWSP034664F1': [4.46501263558197, 50.84321709141105],
 'BXLUCC126937F1': [4.3266903763671545, 50.782080334823156],
 'BXLSCH034089F1': [4.397449948410034, 50.855062290209645],
 'BXLMOL135657B1': [4.333433, 50.849606],
 'BXLSTG127438F1': [4.344949971581502, 50.82720108111752],
 'BXLSCH034012F1': [4.416086337389657, 50.854345665916746],
 'BXLFOR034195F1': [4.324585274895873, 50.81010467829881],
 'BXLBXL034165F1': [4.314504860640823, 50.893188733811755],
 'BXLFOR034198F1': [4.325942522084301, 50.82385757520521],
 'BXLBXL034139B1': [4.367556, 50.842694],
 'BXLMOL034186F1': [4.329834084350586, 50.84949914836653],
 'BXLUCC034681F1': [4.325186111111111, 50.7881611],
 'BXLWSP135477B1': [4.465475174136202, 50.83579704373443],
 'BXLMOL037150B1': [4.336074, 50.861511],
 'BXLWSL036646F1': [4.460077, 50.84725],
 'BXLUCC137997F1': [4.359375, 50.81436],
 'BXLETT135536F1': [4.385382485451682, 50.83949525637519],
 'BXLJET034167F1': [4.333264, 50.876424],
 'BXLAND034237B1': [4.330783, 50.842319],
 'BXLUCC034671F1': [4.382401600919443, 50.77572649590278],
 'BXLSCH034069F1': [4.371366, 50.86957],
 'BXLUCC034153F1': [4.400545202113811, 50.79639820752692],
 'BXLJET031441F1': [4.31401414829809, 50.892990257645266],
 'BXLSTG127016F1': [4.353711850475308, 50.822535569832155],
 'BXLBXL034243F1': [4.328826364418029, 50.89674241394283],
 'BXLIXL126558B1': [4.363400530116102, 50.83585514312423],
 'BXLJET034168F1': [4.334129199537687, 50.87920459735331],
 'BXLSTJ034076F1': [4.355822261263197, 50.85685912905878],
 'BXLFOR034199F1': [4.326983710367238, 50.824061336221305],
 'BXLBXL134406F1': [4.36066716393938, 50.90097761105946],
 'BXLBXL135919B1': [4.367306, 50.842972],
 'BXLUCC137998B1': [4.359248161315918, 50.8143424987793],
 'BXLBXL127896F1': [4.358409329951415, 50.855083383628454],
 'BXLSTG127440F1': [4.344523, 50.827349],
 'BXLJET127936F1': [4.314214323172039, 50.89298473390785],
 'BXLFOR131856F1': [4.321267591194478, 50.82206084406789],
 'BXLFOR034197F1': [4.326335853004577, 50.82389323698994],
 'BXLBXL132637F1': [4.347288495355899, 50.90061275884519],
 'BXLWSP034666F1': [4.46538145767212, 50.84032934950855],
 'BXLBXL034101F1': [4.360454910906814, 50.900988782330245],
 'BXLBXL138178B1': [4.351041793823242, 50.84187316894531],
 'BXLIXL125898F1': [4.365845, 50.833877],
 'BXLAUD133137B1': [4.450661047319716, 50.81801765271052],
 'BXLBXL138017B1': [4.365986860191916, 50.849513418970396],
 'BXLMOL034191F1': [4.344898699825447, 50.863737643005756],
 'BXLBSA034184F1': [4.290277514067757, 50.856020161765436],
 'BXLIXL034124B1': [4.378709009028519, 50.82970623512469],
 'BXLGAN035895B1': [4.316940307617188, 50.877939331513744],
 'BXLIXL126556B1': [4.363806981786268, 50.835569285021],
 'BXLWSL036645F1': [4.458971454014873, 50.848241270422136],
 'BXLIXL126096B1': [4.364001, 50.836881],
 'BXLIXL125839F1': [4.363539, 50.835394],
 'BXLIXL126777B1': [4.36469, 50.835843],
 'BXLBXL031436F1': [4.347469, 50.900644],
 'BXLIXL125797B1': [4.363312500897836, 50.83625219311622],
 'BXLSCH034071F1': [4.365292, 50.86982],
 'BXLIXL126778F1': [4.365371727134614, 50.83663384090913],
 'BXLEVE133177B1': [4.417003, 50.871736],
 'BXLBXL135996F1': [4.358361, 50.832972],
 'BXLIXL135837F1': [4.36685, 50.81701],
 'BXLWAT031457F1': [4.420431366705273, 50.78961844985919],
 'BXLWAT031458F1': [4.420096360249797, 50.78971225566884],
 'BXLSCH135879F1': [4.368278, 50.859361],
 'BXLSTJ125837F1': [4.370984932540893, 50.849402]}

In [12]:
import pickle

In [13]:
pickle.dump(locations, open("../datasets/locations.pkl", "wb"))

In [140]:
def get_adjacency_matrix(distance_df, sensor_ids, normalized_k=0.1):
    """

    :param distance_df: data frame with three columns: [from, to, distance].
    :param sensor_ids: list of sensor ids.
    :param normalized_k: entries that become lower than normalized_k after normalization are set to zero for sparsity.
    :return:
    """
    num_sensors = len(sensor_ids)
    dist_mx = np.zeros((num_sensors, num_sensors), dtype=np.float32)
    dist_mx[:] = np.inf
    # Builds sensor id to index map.
    sensor_id_to_ind = {}
    for i, sensor_id in enumerate(sensor_ids):
        sensor_id_to_ind[sensor_id] = i

    # Fills cells in the matrix with distances.
    for row in distance_df.values:
        if row[0] not in sensor_id_to_ind or row[1] not in sensor_id_to_ind:
            continue
        dist_mx[sensor_id_to_ind[row[0]], sensor_id_to_ind[row[1]]] = row[2]

    # Calculates the standard deviation as theta.
    distances = dist_mx[~np.isinf(dist_mx)].flatten()
    std = distances.std()
    adj_mx = np.exp(-np.square(dist_mx / std))
    # Make the adjacent matrix symmetric by taking the max.
    # adj_mx = np.maximum.reduce([adj_mx, adj_mx.T])

    # Sets entries that lower than a threshold, i.e., k, to zero for sparsity.
    adj_mx[adj_mx < normalized_k] = 0
    return sensor_ids, sensor_id_to_ind, adj_mx

In [142]:
def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance in kilometers between two points
    on the Earth specified in decimal degrees.
    """
    # convert decimal degrees to radians
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    # haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    c = 2 * np.arcsin(np.sqrt(a))
    r = 6371  # Radius of Earth in kilometers. Use 3956 for miles.
    return c * r

def compute_distance_df(locations: dict):
    """
    return a data frame with three columns: [from, to, distance] for all pairs of sensors.
    """
    sensor_ids = list(locations.keys())
    distance_data = []
    for i in range(len(sensor_ids)):
        for j in range(i + 1, len(sensor_ids)):
            from_id = sensor_ids[i]
            to_id = sensor_ids[j]
            lon1, lat1 = locations[from_id]
            lon2, lat2 = locations[to_id]
            distance = haversine(lon1, lat1, lon2, lat2)
            distance_data.append([from_id, to_id, distance])
            distance_data.append([to_id, from_id, distance])  # Add the reverse direction

    distance_df = pd.DataFrame(distance_data, columns=['from', 'to', 'distance'])
    return distance_df

In [143]:
distance_df = compute_distance_df(locations)

In [147]:
distance_df[distance_df["distance"]<5]

                  from              to  distance
0       BXLAND135656B1  BXLAND135417B1  0.161620
1       BXLAND135417B1  BXLAND135656B1  0.161620
2       BXLAND135656B1  BXLMOL034189F1  1.555177
3       BXLMOL034189F1  BXLAND135656B1  1.555177
4       BXLAND135656B1  BXLBXL125638B1  4.502771
...                ...             ...       ...
127793  BXLSTJ125837F1  BXLIXL135837F1  3.613513
127794  BXLWAT031457F1  BXLWAT031458F1  0.025756
127795  BXLWAT031458F1  BXLWAT031457F1  0.025756
127804  BXLSCH135879F1  BXLSTJ125837F1  1.123575
127805  BXLSTJ125837F1  BXLSCH135879F1  1.123575

[58544 rows x 3 columns]

In [156]:
filtered_columns.tolist()

['BXLAND031448F1',
 'BXLAND031450F1',
 'BXLAND031451F1',
 'BXLAND034219F1',
 'BXLAND034220F1',
 'BXLAND034221F1',
 'BXLAND034222F1',
 'BXLAND034224F1',
 'BXLAND034225F1',
 'BXLAND034232F1',
 'BXLAND034237B1',
 'BXLAND034238B1',
 'BXLAND034239F1',
 'BXLAND034240F1',
 'BXLAND034244F1',
 'BXLAND034685F1',
 'BXLAND034686F1',
 'BXLAND036505F1',
 'BXLAND039685F1',
 'BXLAND131286F1',
 'BXLAND131299F1',
 'BXLAND134439F1',
 'BXLAND134656F1',
 'BXLAND134657F1',
 'BXLAND134658F1',
 'BXLAND135417B1',
 'BXLAND135418B1',
 'BXLAND135419B1',
 'BXLAND135656B1',
 'BXLAND135658B1',
 'BXLAND135659B1',
 'BXLAND135936F1',
 'BXLAUD031459F1',
 'BXLAUD034150F1',
 'BXLAUD036804F1',
 'BXLAUD127156F1',
 'BXLAUD133137B1',
 'BXLAUD133166F1',
 'BXLAUD134956F1',
 'BXLAUD134958F1',
 'BXLAUD138737F1',
 'BXLBSA034173F1',
 'BXLBSA034174F1',
 'BXLBSA034175F1',
 'BXLBSA034176F1',
 'BXLBSA034184F1',
 'BXLBSA126899F1',
 'BXLBSA126936F1',
 'BXLBSA131672F1',
 'BXLBSA137640B1',
 'BXLBSA137641B1',
 'BXLBSA137642B1',
 'BXLBSA137643B1',
 'BXLBXL031435F1',
 'BXLBXL031438F1',
 'BXLBXL032497F1',
 'BXLBXL034065F1',
 'BXLBXL034077F1',
 'BXLBXL034078F1',
 'BXLBXL034097F1',
 'BXLBXL034098F1',
 'BXLBXL034099F1',
 'BXLBXL034100F1',
 'BXLBXL034101F1',
 'BXLBXL034102F1',
 'BXLBXL034104F1',
 'BXLBXL034133F1',
 'BXLBXL034134F1',
 'BXLBXL034136F1',
 'BXLBXL034138F1',
 'BXLBXL034144F1',
 'BXLBXL034146F1',
 'BXLBXL034147F1',
 'BXLBXL034148F1',
 'BXLBXL034165F1',
 'BXLBXL034243F1',
 'BXLBXL034245F1',
 'BXLBXL034246B1',
 'BXLBXL034250F1',
 'BXLBXL035825F1',
 'BXLBXL035884F1',
 'BXLBXL035885F1',
 'BXLBXL035886B1',
 'BXLBXL035887F1',
 'BXLBXL036926B1',
 'BXLBXL036927B1',
 'BXLBXL036931F1',
 'BXLBXL036934F1',
 'BXLBXL036945F1',
 'BXLBXL037144B1',
 'BXLBXL037146B1',
 'BXLBXL125635B1',
 'BXLBXL125637B1',
 'BXLBXL125638B1',
 'BXLBXL125716B1',
 'BXLBXL125717B1',
 'BXLBXL127216F1',
 'BXLBXL127256F1',
 'BXLBXL127896F1',
 'BXLBXL127997F1',
 'BXLBXL128057F1',
 'BXLBXL132637F1',
 'BXLBXL133136F1',
 'BXLBXL133452B1',
 'BXLBXL133486B1',
 'BXLBXL134156B1',
 'BXLBXL134405B1',
 'BXLBXL134406F1',
 'BXLBXL134700B1',
 'BXLBXL134998F1',
 'BXLBXL135560F1',
 'BXLBXL135669B1',
 'BXLBXL135670F1',
 'BXLBXL135916F1',
 'BXLBXL135917F1',
 'BXLBXL136779B1',
 'BXLBXL136780F1',
 'BXLBXL136829B1',
 'BXLBXL137276B1',
 'BXLBXL138018B1',
 'BXLBXL138019B1',
 'BXLBXL138020B1',
 'BXLBXL138097B1',
 'BXLBXL138177B1',
 'BXLBXL138178B1',
 'BXLBXL138180B1',
 'BXLETT034018F1',
 'BXLETT034023F1',
 'BXLETT036933F1',
 'BXLETT135536F1',
 'BXLETT135537F1',
 'BXLEVE032496B1',
 'BXLEVE032498B1',
 'BXLEVE032499F1',
 'BXLEVE034011F1',
 'BXLEVE034064F1',
 'BXLEVE035891F1',
 'BXLEVE127976F1',
 'BXLEVE127996F1',
 'BXLEVE128059F1',
 'BXLEVE133176B1',
 'BXLEVE133177B1',
 'BXLEVE134936F1',
 'BXLEVE135713F1',
 'BXLEVE139779B1',
 'BXLFOR034195F1',
 'BXLFOR034198F1',
 'BXLFOR034199F1',
 'BXLFOR034200F1',
 'BXLFOR034205F1',
 'BXLFOR131856F1',
 'BXLFOR131857F1',
 'BXLGAN034170F1',
 'BXLGAN034171F1',
 'BXLGAN034172F1',
 'BXLGAN035894F1',
 'BXLGAN035895B1',
 'BXLGAN037166B1',
 'BXLGAN134660F1',
 'BXLIXL034124B1',
 'BXLIXL034127F1',
 'BXLIXL034130B1',
 'BXLIXL034140F1',
 'BXLIXL125796B1',
 'BXLIXL125839F1',
 'BXLIXL125896F1',
 'BXLIXL125897B1',
 'BXLIXL125898F1',
 'BXLIXL126096B1',
 'BXLIXL126556B1',
 'BXLIXL126557F1',
 'BXLIXL126558B1',
 'BXLIXL127916F1',
 'BXLIXL135836F1',
 'BXLIXL138098F1',
 'BXLJET031440F1',
 'BXLJET034164F1',
 'BXLJET034167F1',
 'BXLJET034168F1',
 'BXLJET126903F1',
 'BXLJET126904F1',
 'BXLJET127338F1',
 'BXLJET127936F1',
 'BXLJET135757B1',
 'BXLKOE031685F1',
 'BXLKOE034178F1',
 'BXLKOE034179F1',
 'BXLKOE037164B1',
 'BXLKOE037165B1',
 'BXLKOE037167B1',
 'BXLKOE126857B1',
 'BXLKOE126918F1',
 'BXLKOE126923F1',
 'BXLKOE126924F1',
 'BXLKOE126925F1']

In [159]:
filtered_distance = distance_df[distance_df["from"].isin(filtered_columns) & distance_df["to"].isin(filtered_columns)]

In [160]:
filtered_columns

Index(['BXLAND031448F1', 'BXLAND031450F1', 'BXLAND031451F1', 'BXLAND034219F1',
       'BXLAND034220F1', 'BXLAND034221F1', 'BXLAND034222F1', 'BXLAND034224F1',
       'BXLAND034225F1', 'BXLAND034232F1',
       ...
       'BXLKOE034178F1', 'BXLKOE034179F1', 'BXLKOE037164B1', 'BXLKOE037165B1',
       'BXLKOE037167B1', 'BXLKOE126857B1', 'BXLKOE126918F1', 'BXLKOE126923F1',
       'BXLKOE126924F1', 'BXLKOE126925F1'],
      dtype='object', length=195)

In [161]:
adj = get_adjacency_matrix(filtered_distance, filtered_columns.tolist(), normalized_k=0.1)

In [164]:
import pickle

In [165]:
pickle.dump(adj, open("adjacency_matrix.pkl", "wb"))

In [106]:
fff = pickle.load(open('/home/seyed/PycharmProjects/step/STEP/datasets/Bru/columns_index_data_dataset.pkl', 'rb'))

In [108]:
fff.head()

0    BXLAND031448F1
1    BXLAND031450F1
2    BXLAND031451F1
3    BXLAND034219F1
4    BXLAND034220F1
dtype: object

In [104]:
with open('../datasets/pred_horizon_dict.pkl', 'rb') as f:
    pred_horizon_dict = pickle.load(f)
with open('../datasets/pred_rolling_dict_v1.pkl', 'rb') as f:
    pred_rolling_dict = pickle.load(f)
with open('../datasets/dataset_freq_v1.pkl', 'rb') as f:
    dataset_freq_dict = pickle.load(f)

In [105]:
pred_rolling_dict["brussels"]

24

In [97]:
dataset_freq_dict["brussels"] = "5min"

In [98]:
pred_horizon_dict["brussels"], pred_rolling_dict["brussels"] = pred_horizon_dict["pems03_flow"], pred_rolling_dict["pems03_flow"]

In [99]:
pickle.dump(pred_horizon_dict, open('../datasets/pred_horizon_dict_v1.pkl', 'wb'))
pickle.dump(pred_rolling_dict, open('../datasets/pred_rolling_dict_v1.pkl', 'wb'))
pickle.dump(dataset_freq_dict, open('../datasets/dataset_freq_v1.pkl', 'wb'))